### ISSUE TITLE
Should we use Ubuntu or RHEL UBI instead of CentOS?

### ISSUE THREAD

**Issue by shawndwells** [CrowdStrike/cloud-tools-image#1]
Ref: 
https://github.com/CrowdStrike/cloud-tools-image/blob/451c61f8118969b5b214a4cef2e874d844668a40/Dockerfile#L1

Current Dockerfile uses CentOS which does not have FIPS and other things for regulated industries. Would it make sense to switch to either Ubuntu or RHEL UBI?

**Comment by redhatrises** [comment]
Something I have been thinking about enhancing the CrowdStrike/Dockerfiles project is the ability to specify the image to make. For example:

```
make rhel VERSION=8
```

Might be a useful idea here. Feel free to ignore if it is just terrible.

**Comment by shawndwells** [comment]
Would be great to spin container images on all the Linux distros we support
