### ISSUE TITLE
falcon-container-sensor-push issue with FALCON_IMAGE_URI

### ISSUE THREAD

**Issue by carlosmmatos** [CrowdStrike/cloud-tools-image#38]
**Submitted on behalf of a consumer

When running the `falcon-container-sensor-push` script, it looks like there is a potential issue when the FALCON_IMAGE_URI contains a URI that has a format such as:

`112233445566.dkr.ecr.us-example-1.amazonaws.com/falcon-sensor [112233445566.dkr.ecr.us-example-1.amazonaws.com]`

While this is a valid format that will execute fine when ran explicitly:
`$ falcon-container-sensor-push 112233445566.dkr.ecr.us-example-1.amazonaws.com/falcon-sensor [112233445566.dkr.ecr.us-example-1.amazonaws.com]`

It fails when setting the variable as documented in [EKS Fargate Guide](https://github.com/CrowdStrike/Cloud-AWS/blob/main/Container%20Security/eks-implementation-guide.md#step-3-push-the-falcon-sensor-image-to-the-repository)

This is probably something that we can fix by either updating the documentation to reflect this edge case where characters need to be escaped, or maybe we handle it in the script itself.

**Comment by isimluk** [comment]
Thx, can you help me understand from where the ` [1234...]` part comes from?

**Comment by isimluk** [comment]
I have quickly re-run the example from the EKS Fargate guide
```
FALCON_IMAGE_URI=$(aws ecr describe-repositories --region $CLOUD_REGION | jq -r '.repositories[] | select(.repositoryName=="falcon-sensor") | .repositoryUri')
echo $FALCON_IMAGE_URI
```
and it seems to produce valid docker repo location. I must be missing something obvious... ? 🤷

**Comment by isimluk** [comment]
(I am using hosted/stock/non-outpost AWS)

**Comment by carlosmmatos** [comment]
so just doing some testing - my guess is that we can solve this issue by just updating the documentation to read:
```bash
FALCON_IMAGE_URI=$(aws ecr describe-repositories --region $CLOUD_REGION | jq -r '.repositories[] | select(.repositoryName=="falcon-sensor") | .repositoryUri')
falcon-container-sensor-push "${FALCON_IMAGE_URI}"
```

That should properly encapsulate the variable.
